import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

// import { ThemeProvider } from "@/provider/ThemeProvider";
import StreamProvider from "@/provider/StreamProvider";

const font = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "AI Webinars",
  description: "Generated by create next app",
  icons: ["/clerk.png"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${font.variable} antialiased`}>
          <StreamProvider>
            {/* <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange> */}
            {children}
            <Toaster richColors />
            {/* </ThemeProvider> */}
          </StreamProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
